return {
  { "catppuccin/nvim" },
  { "folke/tokyonight.nvim" },
  { "rebelot/kanagawa.nvim" },
  { "ellisonleao/gruvbox.nvim" },
  { "savq/melange-nvim" },
  { "Shatur/neovim-ayu" },
  { "sainnhe/edge" },
  { "sainnhe/sonokai" },
  { "EdenEast/nightfox.nvim" },
  { "bluz71/vim-nightfly-colors" },
  { "tiagovla/tokyodark.nvim" },
  {
    "LazyVim/LazyVim",
    opts = {
      -- colorscheme = "edge",
      -- colorscheme = "catppuccin-mocha",
      colorscheme = "tokyodark",
      -- colorscheme = "tokyonight-night",
      -- colorscheme = "kanagawa",
      -- colorscheme = "gruvbox",
      -- colorscheme = "ayu-mirage",
    },
  },
}
